import React, { useState, useEffect } from "react";
import { Modal } from "antd";
import {
  SafetyCertificateOutlined,
  CloseOutlined,
  WarningOutlined,
  CopyOutlined,
  CheckOutlined,
  ExclamationCircleOutlined,
  LockOutlined,
  GlobalOutlined,
  CheckCircleOutlined,
  GitlabOutlined,
} from "@ant-design/icons";
import ReactMarkdown from "react-markdown";
import { SecurityAuditResult } from "@shared/types";
import { useToast } from "./ToastContext";

interface SecurityAuditModalProps {
  visible: boolean;
  onClose: () => void;
  result: SecurityAuditResult | null;
  loading: boolean;
}

export const SecurityAuditModal: React.FC<SecurityAuditModalProps> = ({
  visible,
  onClose,
  result,
  loading,
}) => {
  const [loadingStep, setLoadingStep] = useState(0);
  const [isCopied, setIsCopied] = useState(false);
  const [isCreatingIssue, setIsCreatingIssue] = useState(false);
  const { showToast } = useToast();

  const steps = [
    "Scanning for hardcoded secrets...",
    "Analyzing for SQL injection...",
    "Checking XSS vulnerabilities...",
    "Validating dependency security...",
    "Checking compliance (GDPR/HIPAA)...",
    "Finalizing security report...",
  ];

  useEffect(() => {
    if (!loading) {
      setLoadingStep(0);
      return;
    }

    const interval = setInterval(() => {
      setLoadingStep((prev) => (prev < steps.length - 1 ? prev + 1 : prev));
    }, 1000);

    return () => clearInterval(interval);
  }, [loading]);

  const handleCopyReport = async () => {
    if (!result) return;

    const reportText = `
# AI Security Audit Report
Status: ${result.isSafe ? "SAFE" : "RISKS DETECTED"}

## Summary
${result.summary}

## Findings (${result.findings.length})
${result.findings
  .map(
    (f) =>
      `- [${f.type.toUpperCase()}] (${f.severity}): ${f.message}\n  File: ${f.file}\n  Remediation: ${f.remediation}`,
  )
  .join("\n\n")}
    `.trim();

    try {
      await window.gitcanopyAPI.copyToClipboard(reportText);
      setIsCopied(true);
      showToast("Security report copied", "success", 2000);
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      showToast("Failed to copy report", "error");
    }
  };

  const handleCreateIssue = async () => {
    if (!result || !result.findings.length) return;
    setIsCreatingIssue(true);

    try {
      const title = `Security Audit Findings: ${result.findings.length} Issues Detected`;
      const description = `
# Automated Security Audit Report

**Summary:** ${result.summary}

## Findings

${result.findings
  .map(
    (f) => `### ${f.message}
- **Type:** ${f.type}
- **Severity:** ${f.severity}
- **File:** \`${f.file}\`
- **Remediation:** ${f.remediation}

\`\`\`javascript
${f.snippet || "// No snippet provided"}
\`\`\`
`,
  )
  .join("\n")}

---
*Report generated by GitCanopy Guardian Agent*
      `.trim();

      const { webUrl } = await window.gitcanopyAPI.createGitLabIssue(
        title,
        description,
      );
      showToast("GitLab Issue Created Successfully!", "success");
      window.gitcanopyAPI.openExternal(webUrl);
    } catch (error: any) {
      showToast(error.message || "Failed to create issue", "error");
    } finally {
      setIsCreatingIssue(false);
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case "critical":
        return "text-red-600 bg-red-600/10 border-red-600/20";
      case "high":
        return "text-orange-600 bg-orange-600/10 border-orange-600/20";
      case "medium":
        return "text-yellow-600 bg-yellow-600/10 border-yellow-600/20";
      default:
        return "text-blue-600 bg-blue-600/10 border-blue-600/20";
    }
  };

  const getIcon = (type: string) => {
    switch (type) {
      case "secret":
        return <LockOutlined />;
      case "vulnerability":
        return <ExclamationCircleOutlined />;
      case "compliance":
        return <GlobalOutlined />;
      default:
        return <SafetyCertificateOutlined />;
    }
  };

  return (
    <Modal
      title={null}
      open={visible}
      onCancel={onClose}
      footer={null}
      width={700}
      centered
      classNames={{
        content:
          "p-0 overflow-hidden bg-white dark:bg-zed-dark-bg rounded-xl border border-zed-border dark:border-zed-dark-border shadow-2xl",
        mask: "backdrop-blur-md bg-black/50",
      }}
      closeIcon={null}
    >
      {loading ? (
        <div className="h-96 flex flex-col items-center justify-center bg-zed-bg dark:bg-zed-dark-bg">
          <div className="relative mb-8">
            <div className="w-16 h-16 border-2 border-zed-accent/20 rounded-full animate-ping absolute" />
            <div className="w-16 h-16 border-b-2 border-zed-accent rounded-full animate-spin" />
            <SafetyCertificateOutlined className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-xl text-zed-accent" />
          </div>
          <div className="text-center space-y-3">
            <h3 className="text-[10px] font-black uppercase tracking-[0.3em] text-zed-accent">
              Pre-Push Guardian Active
            </h3>
            <p className="text-sm font-medium text-zed-text dark:text-zed-dark-text animate-pulse">
              {steps[loadingStep]}
            </p>
          </div>
        </div>
      ) : result ? (
        <div className="flex flex-col max-h-[90vh]">
          {/* Header */}
          <div
            className={`px-8 py-6 border-b border-zed-border dark:border-zed-dark-border flex items-start justify-between ${result.isSafe ? "bg-emerald-50/50 dark:bg-emerald-500/5" : "bg-red-50/50 dark:bg-red-500/5"}`}
          >
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-4">
                <div
                  className={`p-2 rounded-lg ${result.isSafe ? "bg-emerald-100 text-emerald-600" : "bg-red-100 text-red-600"}`}
                >
                  {result.isSafe ? (
                    <CheckCircleOutlined className="text-2xl" />
                  ) : (
                    <WarningOutlined className="text-2xl" />
                  )}
                </div>
                <div>
                  <h2 className="text-lg font-bold tracking-tight text-zed-text dark:text-zed-dark-text">
                    {result.isSafe
                      ? "Security Audit Passed"
                      : "Security Risks Detected"}
                  </h2>
                  <p className="text-xs text-zed-muted opacity-70">
                    {result.findings.length} findings identified in staged
                    changes
                  </p>
                </div>
              </div>
              <div className="prose dark:prose-invert prose-sm max-w-none text-zed-text/80 dark:text-zed-dark-text/80">
                <ReactMarkdown>{result.summary}</ReactMarkdown>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-black/5 dark:hover:bg-white/5 rounded-full text-zed-muted transition-colors"
            >
              <CloseOutlined />
            </button>
          </div>

          {/* Findings List */}
          <div className="flex-1 overflow-y-auto bg-gray-50/50 dark:bg-black/20">
            {result.findings.length === 0 ? (
              <div className="py-20 flex flex-col items-center justify-center opacity-40">
                <SafetyCertificateOutlined className="text-4xl mb-4 text-emerald-500" />
                <span className="text-xs font-bold uppercase tracking-widest">
                  No vulnerabilities found
                </span>
              </div>
            ) : (
              <div className="divide-y divide-zed-border/30 dark:divide-zed-dark-border/30">
                {result.findings.map((f, i) => (
                  <div
                    key={i}
                    className="px-8 py-6 hover:bg-white dark:hover:bg-white/[0.02] transition-colors group"
                  >
                    <div className="flex items-start gap-5">
                      <div
                        className={`mt-1 p-2 rounded-lg text-lg ${getSeverityColor(f.severity)}`}
                      >
                        {getIcon(f.type)}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="text-[10px] font-black uppercase tracking-widest text-zed-muted/60">
                            {f.type}
                          </span>
                          <span
                            className={`text-[9px] font-bold uppercase px-2 py-0.5 rounded border ${getSeverityColor(f.severity)}`}
                          >
                            {f.severity}
                          </span>
                          <span
                            className="text-[10px] font-mono opacity-40 ml-auto truncate"
                            title={f.file}
                          >
                            {f.file}
                          </span>
                        </div>
                        <h4 className="text-sm font-bold mb-2 text-zed-text dark:text-zed-dark-text">
                          {f.message}
                        </h4>

                        {f.snippet && (
                          <div className="mb-3 bg-black/5 dark:bg-black/40 rounded p-2 font-mono text-[11px] overflow-x-auto border border-black/5 dark:border-white/5">
                            <code className="text-red-500 dark:text-red-400">
                              {f.snippet}
                            </code>
                          </div>
                        )}

                        {f.remediation && (
                          <div className="flex items-start gap-2 text-xs bg-emerald-500/5 border border-emerald-500/10 p-2.5 rounded-lg text-emerald-700 dark:text-emerald-400">
                            <CheckCircleOutlined className="mt-0.5 shrink-0" />
                            <div>
                              <span className="font-bold mr-1">
                                Remediation:
                              </span>
                              {f.remediation}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="px-8 py-4 border-t border-zed-border dark:border-zed-dark-border bg-white dark:bg-zed-dark-bg flex items-center justify-between">
            <div className="flex items-center gap-2 text-[10px] font-medium text-zed-muted opacity-60">
              <SafetyCertificateOutlined className="text-emerald-500" />
              <span>Automated Security Guard powered by Google Gemini</span>
            </div>
            <div className="flex items-center gap-4">
              {result.findings.length > 0 && (
                <button
                  onClick={handleCreateIssue}
                  disabled={isCreatingIssue}
                  className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-widest text-zed-muted hover:text-zed-accent transition-colors disabled:opacity-50"
                >
                  {isCreatingIssue ? (
                    <div className="w-3 h-3 border border-current border-t-transparent rounded-full animate-spin" />
                  ) : (
                    <GitlabOutlined />
                  )}
                  {isCreatingIssue ? "Creating..." : "Create Issue"}
                </button>
              )}
              <button
                onClick={handleCopyReport}
                className={`flex items-center gap-2 text-[11px] font-bold uppercase tracking-widest transition-all ${isCopied ? "text-emerald-500" : "text-zed-muted hover:text-zed-text"}`}
              >
                {isCopied ? <CheckOutlined /> : <CopyOutlined />}
                {isCopied ? "Copied" : "Copy Report"}
              </button>
              <button
                onClick={onClose}
                className="bg-zed-text dark:bg-white text-zed-bg dark:text-black px-4 py-1.5 rounded text-[11px] font-bold uppercase tracking-widest hover:opacity-90 transition-all shadow-sm"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </Modal>
  );
};
